### ISSUE TITLE
NetworkResponseDecodingFailure

### ISSUE THREAD

**Issue by WBP20** [passbolt/mobile-passbolt-ios#8]
Hello, I face a another bug on the app today.

Device : Iphone
OS : 16.7.7
App : 1.17.4

I cannot refresh data on my app.
I got the error "Network Response Decoding Failure"

```
2024-04-01 19:19:47] ...users data refresh failed!
[2024-04-01 19:19:47] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
[2024-04-01 19:19:47] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-04-01 19:19:47] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
```
This new problem had never occured before. 
I did create a new entry right before this new problem. 

Any solution for this ?

**Comment by elalitarek** [comment]
+1 

IOS17.4.1 
App 1.17.4

**Comment by elalitarek** [comment]
> Hello, I face a another bug on the app today.
> 
> Device : Iphone OS : 16.7.7 App : 1.17.4
> 
> I cannot refresh data on my app. I got the error "Network Response Decoding Failure"
> 
> ```
> 2024-04-01 19:19:47] ...users data refresh failed!
> [2024-04-01 19:19:47] ⚠️ NetworkResponseDecodingFailure
> DiagnosticsContext:
> •Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
> •...account profile data update failed! PassboltApp/MainTabsController.swift:101
> [2024-04-01 19:19:47] ⚠️ NetworkResponseDecodingFailure
> DiagnosticsContext:
> •Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
> [2024-04-01 19:19:47] ⚠️ NetworkResponseDecodingFailure
> DiagnosticsContext:
> •Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
> ```
> 
> This new problem had never occured before. I did create a new entry right before this new problem.
> 
> Any solution for this ?

Had the same issue, but after updating the server it works.

**Comment by magicman0978** [comment]
I'm Having the same issue. any fix yet? my server is up to date.
![IMG_5073](https://github.com/passbolt/mobile-passbolt-ios/assets/23557356/87533b5e-7f76-4f85-99ef-f87c7fd6b216)

**Comment by elalitarek** [comment]
> I'm Having the same issue. any fix yet? my server is up to date. ![IMG_5073](https://private-user-images.githubusercontent.com/23557356/324007353-87533b5e-7f76-4f85-99ef-f87c7fd6b216.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mzk3ODEsIm5iZiI6MTcxMzUzOTQ4MSwicGF0aCI6Ii8yMzU1NzM1Ni8zMjQwMDczNTMtODc1MzNiNWUtN2Y3Ni00Zjg1LTk5ZWYtZjg3YzdmZDZiMjE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE1MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZGY4MTJhYTU1NWEzYzliMzMxNjgyNmZhZjJhNzg5MGFmNGI0NTAzMTMxMDBjM2UwMDFmMmY4YWNkYjFiNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3hEVLFfWBxG3n3Tg9sHh-sf7D3yD2PLONP96uER5lZI)

What about reading the above? 
Update the server -.-

**Comment by jlecordier** [comment]
Same issue here

The server is probably not up to date, but should this behavior be normal ?

Knowing that with the same server, the Android app is working fine ?

**Comment by abhimanyu95** [comment]
I am also having the same issue. Android app is working fine, I had checked on Android 14 and Android 12

Log 1

Passbolt:
Device: iPhone
OS: 17.4.1
App: 1.18.0
----------
[2024-05-08 05:01:57] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-05-08 05:01:57] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-05-08 05:03:06] Wiping passphrase cache...
[2024-05-08 05:03:57] Requesting authorization...
[2024-05-08 05:03:57] [A77E5ACE-E80C-4D63-AC2F-B9DBC0E8B50D] HTTP GET /img/avatar/user_medium.png
[2024-05-08 05:03:58] [A77E5ACE-E80C-4D63-AC2F-B9DBC0E8B50D] HTTP 200 /img/avatar/user_medium.png
[2024-05-08 05:04:08] Beginning authorization...
[2024-05-08 05:04:08] ...reusing access token...
[2024-05-08 05:04:08] Passphrase provided...
[2024-05-08 05:04:08] ...authorization succeeded!
[2024-05-08 05:04:08] Updating account profile data...
[2024-05-08 05:04:09] [CB4416B2-4B28-4050-BC4D-933F963DE7E5] HTTP GET /users/3b04018d-6a4d-4d8c-b074-d3eb94f08dce.json
[2024-05-08 05:04:09] [CB4416B2-4B28-4050-BC4D-933F963DE7E5] HTTP 200 /users/3b04018d-6a4d-4d8c-b074-d3eb94f08dce.json
[2024-05-08 05:04:10] ...account profile data updated!
[2024-05-08 05:05:31] Requesting authorization...
[2024-05-08 05:05:31] [156D9C33-713D-4F55-A35C-C0EE62C336E1] HTTP GET /img/avatar/user_medium.png
[2024-05-08 05:05:31] [67169C24-BF5A-46F3-BC40-F2C79435F5F3] HTTP GET /img/avatar/user_medium.png
[2024-05-08 05:05:32] [67169C24-BF5A-46F3-BC40-F2C79435F5F3] HTTP 200 /img/avatar/user_medium.png
[2024-05-08 05:05:32] [156D9C33-713D-4F55-A35C-C0EE62C336E1] HTTP 200 /img/avatar/user_medium.png
[2024-05-08 05:05:41] Beginning authorization...
[2024-05-08 05:05:41] ...reusing access token...
[2024-05-08 05:05:41] Passphrase provided...
[2024-05-08 05:05:41] ...authorization succeeded!
[2024-05-08 05:05:41] Updating account profile data...
[2024-05-08 05:05:41] [35CB8BC2-9156-4F09-AEBE-97AD23798ED1] HTTP GET /users/3b04018d-6a4d-4d8c-b074-d3eb94f08dce.json

Log 2 

Passbolt:
Device: iPhone
OS: 16.7.7
App: 1.18.0
----------
[2024-05-08 05:22:46] Completing account transfer...
[2024-05-08 05:22:47] Verifying data integrity...
[2024-05-08 05:22:47] ...data integrity verification finished
[2024-05-08 05:22:47] Beginning authorization...
[2024-05-08 05:22:47] ...creating new access token...
[2024-05-08 05:22:47] ...fetching server public PGP key...
[2024-05-08 05:22:47] ...fetching server public RSA key...
[2024-05-08 05:22:47] [E267167E-C5DB-4713-8BC9-09BE495CCB24] HTTP GET /auth/verify.json
[2024-05-08 05:22:47] [021461C6-43A9-49F9-951F-6EE4061E156E] HTTP GET /auth/jwt/rsa.json
[2024-05-08 05:22:48] [E267167E-C5DB-4713-8BC9-09BE495CCB24] HTTP 200 /auth/verify.json
[2024-05-08 05:22:48] Local timestamp: 1715145768
[2024-05-08 05:22:48] Server timestamp: 1715145767
[2024-05-08 05:22:48] Using time diff for session: -2
[2024-05-08 05:22:48] ...verifying server public PGP key...
[2024-05-08 05:22:48] [021461C6-43A9-49F9-951F-6EE4061E156E] HTTP 200 /auth/jwt/rsa.json
[2024-05-08 05:22:48] ...preparing authorization challenge...
[2024-05-08 05:22:48] [D5A4EBDB-D6E6-4F61-9C17-03F69C35B8AF] HTTP POST /auth/jwt/login.json
[2024-05-08 05:22:48] [D5A4EBDB-D6E6-4F61-9C17-03F69C35B8AF] HTTP 200 /auth/jwt/login.json
[2024-05-08 05:22:49] Session created...
[2024-05-08 05:22:49] ...authorization succeeded!
[2024-05-08 05:22:49] ...account transfer succeeded!
[2024-05-08 05:22:49] Session auto locking enabled!
[2024-05-08 05:22:49] Verifying data integrity...
[2024-05-08 05:22:49] ...data integrity verification finished
[2024-05-08 05:22:49] Fetching server configuration...
[2024-05-08 05:22:49] [B5F2EF28-F625-4648-9CEC-970F8C7EE457] HTTP GET /settings.json
[2024-05-08 05:22:49] [B5F2EF28-F625-4648-9CEC-970F8C7EE457] HTTP 200 /settings.json
[2024-05-08 05:22:49] ...server configuration fetched!
[2024-05-08 05:22:49] Fetching rbacs configuration...
[2024-05-08 05:22:49] [01C9110C-727B-46A2-86F3-076FE5675548] HTTP GET /rbacs/me.json
[2024-05-08 05:22:49] [01C9110C-727B-46A2-86F3-076FE5675548] HTTP 200 /rbacs/me.json
[2024-05-08 05:22:49] ...rbacs configuration fetched!
[2024-05-08 05:22:50] [5ADC4423-51E5-49D2-88AB-9604BBD5DB6A] HTTP GET /lookup
[2024-05-08 05:22:50] [5ADC4423-51E5-49D2-88AB-9604BBD5DB6A] HTTP 200 /lookup
[2024-05-08 05:22:50] Refreshing users data...
[2024-05-08 05:22:50] [5DAD132D-1AFE-40A6-B071-296C05B42D74] HTTP GET /users.json
[2024-05-08 05:22:50] Updating account profile data...
[2024-05-08 05:22:50] [DF8F5EE1-5CA9-41E6-8900-03847E2F28AB] HTTP GET /users/3b04018d-6a4d-4d8c-b074-d3eb94f08dce.json
[2024-05-08 05:22:50] [522C3ECD-4812-4423-9730-CE344276FEA4] HTTP GET /img/avatar/user_medium.png
[2024-05-08 05:22:50] [DF8F5EE1-5CA9-41E6-8900-03847E2F28AB] HTTP 200 /users/3b04018d-6a4d-4d8c-b074-d3eb94f08dce.json
[2024-05-08 05:22:50] ...account profile data updated!
[2024-05-08 05:22:50] [5DAD132D-1AFE-40A6-B071-296C05B42D74] HTTP 200 /users.json
[2024-05-08 05:22:50] ...users data refresh finished!
[2024-05-08 05:22:50] Refreshing user groups data...
[2024-05-08 05:22:50] [A7C606C6-1597-4FE6-8DE2-544B4AEAE115] HTTP GET /groups.json
[2024-05-08 05:22:50] [A7C606C6-1597-4FE6-8DE2-544B4AEAE115] HTTP 200 /groups.json
[2024-05-08 05:22:50] ...user groups data refresh finished!
[2024-05-08 05:22:50] Refreshing folders data...
[2024-05-08 05:22:50] [9DD5618C-C488-471F-BE98-829B80FE843A] HTTP GET /folders.json
[2024-05-08 05:22:50] [522C3ECD-4812-4423-9730-CE344276FEA4] HTTP 200 /img/avatar/user_medium.png
[2024-05-08 05:22:50] [17C9BA8C-2759-4718-B4C6-82A33BD36D28] HTTP GET /img/avatar/user_medium.png
[2024-05-08 05:22:51] [17C9BA8C-2759-4718-B4C6-82A33BD36D28] HTTP 200 /img/avatar/user_medium.png
[2024-05-08 05:22:51] [9DD5618C-C488-471F-BE98-829B80FE843A] HTTP 200 /folders.json
[2024-05-08 05:22:51] ...folders data refresh finished!
[2024-05-08 05:22:51] Refreshing resources data...
[2024-05-08 05:22:51] [5C28480A-0CFD-4275-97E5-7CA94DA035B5] HTTP GET /resource-types.json
[2024-05-08 05:22:51] [5C28480A-0CFD-4275-97E5-7CA94DA035B5] HTTP 200 /resource-types.json
[2024-05-08 05:22:51] [E07CC17E-D5C9-4F3D-A3F0-9C70448AD960] HTTP GET /resources.json
[2024-05-08 05:22:52] [E07CC17E-D5C9-4F3D-A3F0-9C70448AD960] HTTP 200 /resources.json
[2024-05-08 05:22:52] ...resources data refresh failed!
[2024-05-08 05:22:52] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-05-08 05:22:52] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86

**Comment by scadra** [comment]
Hello everyone,

First of all I'd like to apologize for the wait and thank you for your patience. We take this bug seriously and are eager to find a solution as soon as possible. 

@WBP20  and @jlecordier has your problem been solved? We know that there was a problem with version 17.4.X of the application and we have tried to resolve it in version 18.0.0.

@abhimanyu95 , I see that the problem persists with version 18.0.0, in order to solve the problem as soon as possible, could you please tell us the server version used?

**Comment by abhimanyu95** [comment]
@scadra Here is the version.
![image](https://github.com/passbolt/mobile-passbolt-ios/assets/70148484/3aa5b170-aeef-49f1-ad2c-a593ac80cf45)

**Comment by jlecordier** [comment]
Hi @scadra ,

The issue is not solved here with these versions :
- iOS : 17.5.1
- App iOS : 1.18.0
- Web app : 4.8.1 (working fine)
- Server : 4.4.2 (Android apps are working fine)

**Comment by jlecordier** [comment]
I confirm that my problem was solved by upgrading the server to 4.8.0. But my point stands : 

> Same issue here

> The server is probably not up to date, but should this behavior be normal ?

> Knowing that with the same server, the Android app is working fine ?

**Comment by rikwillems** [comment]
Updating the Docker container to 4.8.0.1 and the latest iOS app resolved this issue for us. Thank you!

**Comment by abhimanyu95** [comment]
After updating passbolt server to 4.8.0 my issue got resolved.
Thanks

**Comment by scadra** [comment]
@jlecordier,  @abhimanyu95, First of all, thank you for your replies. This behavior is not supposed to happen, we have found a fix to support server versions below the password expiry feature. This fix is ready for release and we should release it ASAP.

If you can upgrade the passbolt server like mentioned by @rikwillems and @elalitarek it should fix the issue. 

Thanks all

**Comment by scadra** [comment]
Hey, @elalitarek @jlecordier 

The release 18.1.0 has been released and should fix this issue. 

Thanks again for this report !

**Comment by Takalele** [comment]
@scadra 
Unfortunately the issue is still there, i'm using the docker version - 4.9.0-1 and traefik as reverse proxy.
IOS Versions: 16.3, 16.7.9 and 17.5.1
App Version: 1.19.0

Logs:

```
Passbolt:
Device: iPad
OS: 16.3
App: 1.19.0
[2024-08-03 10:36:32] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
[2024-08-03 10:36:32] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-08-03 10:36:32] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-08-03 10:43:28] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
[2024-08-03 10:46:02] Wiping passphrase cache...
[2024-08-03 10:56:22] Requesting authorization...
[2024-08-03 10:56:22] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 10:56:22] Beginning authorization...
[2024-08-03 10:56:23] [redacted] HTTP 200 /img/avatar/user_medium.png
[2024-08-03 10:56:24] Access token expired...
[2024-08-03 10:56:24] ...refreshing access token...
[2024-08-03 10:56:24] [redacted] HTTP POST /auth/jwt/refresh.json
[2024-08-03 10:56:24] [redacted] HTTP 200 /auth/jwt/refresh.json
[2024-08-03 10:56:24] Session refreshed...
[2024-08-03 10:56:24] ...authorization succeeded!
[2024-08-03 10:56:24] Updating account profile data...
[2024-08-03 10:56:24] [redacted] HTTP GET /users/user-redacted.json
[2024-08-03 10:56:24] [redacted] HTTP 200 /users/user-redacted.json
[2024-08-03 10:56:24] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
[2024-08-03 10:57:01] Wiping passphrase cache...
[2024-08-03 10:57:03] Requesting authorization...
[2024-08-03 10:57:03] Beginning authorization...
[2024-08-03 10:57:03] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 10:57:04] [redacted] HTTP 200 /img/avatar/user_medium.png
[2024-08-03 10:57:09] ...reusing access token...
[2024-08-03 10:57:09] Passphrase provided...
[2024-08-03 10:57:09] ...authorization succeeded!
[2024-08-03 10:57:09] Updating account profile data...
[2024-08-03 10:57:10] [redacted] HTTP GET /users/user-redacted.json
[2024-08-03 10:57:10] [redacted] HTTP 200 /users/user-redacted.json
[2024-08-03 10:57:10] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
[2024-08-03 10:58:01] Wiping passphrase cache...
[2024-08-03 10:58:03] Requesting authorization...
[2024-08-03 10:58:03] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 10:58:03] Beginning authorization...
[2024-08-03 10:58:03] [redacted] HTTP 200 /img/avatar/user_medium.png
[2024-08-03 10:58:05] ...reusing access token...
[2024-08-03 10:58:05] Passphrase provided...
[2024-08-03 10:58:05] ...authorization succeeded!
[2024-08-03 10:58:05] Updating account profile data...
[2024-08-03 10:58:05] [redacted] HTTP GET /users/user-redacted.json
```

```
Passbolt:
Device: iPad
OS: 16.7.9
App: 1.19.0
[2024-08-03 11:26:06] Initializing the app...
[2024-08-03 11:26:06] ...app initialization completed!
[2024-08-03 11:26:06] Verifying data integrity...
[2024-08-03 11:26:06] ...data integrity verification finished
[2024-08-03 11:26:07] [redacted] HTTP GET /lookup
[2024-08-03 11:26:07] [redacted] HTTP 200 /lookup
[2024-08-03 11:26:07] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 11:26:07] Beginning authorization...
[2024-08-03 11:26:08] [redacted] HTTP 200 /img/avatar/user_medium.png
[2024-08-03 11:26:09] ...creating new access token...
[2024-08-03 11:26:09] ...fetching server public PGP key...
[2024-08-03 11:26:09] [redacted] HTTP GET /auth/verify.json
[2024-08-03 11:26:09] ...fetching server public RSA key...
[2024-08-03 11:26:09] [redacted] HTTP GET /auth/jwt/rsa.json
[2024-08-03 11:26:10] [redacted] HTTP 200 /auth/verify.json
[2024-08-03 11:26:10] Local timestamp: 1722684370
[2024-08-03 11:26:10] Server timestamp: 1722684370
[2024-08-03 11:26:10] Using time diff for session: -1
[2024-08-03 11:26:10] ...verifying server public PGP key...
[2024-08-03 11:26:10] ...preparing authorization challenge...
[2024-08-03 11:26:10] [redacted] HTTP 200 /auth/jwt/rsa.json
[2024-08-03 11:26:10] [redacted] HTTP POST /auth/jwt/login.json
[2024-08-03 11:26:10] [redacted] HTTP 200 /auth/jwt/login.json
[2024-08-03 11:26:10] Session created...
[2024-08-03 11:26:10] ...authorization succeeded!
[2024-08-03 11:26:10] Session auto locking enabled!
[2024-08-03 11:26:10] Verifying data integrity...
[2024-08-03 11:26:10] ...data integrity verification finished
[2024-08-03 11:26:10] Fetching server configuration...
[2024-08-03 11:26:10] [redacted] HTTP GET /settings.json
[2024-08-03 11:26:10] [redacted] HTTP 200 /settings.json
[2024-08-03 11:26:10] ...server configuration fetched!
[2024-08-03 11:26:10] Fetching rbacs configuration...
[2024-08-03 11:26:10] [redacted] HTTP GET /rbacs/me.json
[2024-08-03 11:26:10] [redacted] HTTP 200 /rbacs/me.json
[2024-08-03 11:26:10] ...rbacs configuration fetched!
[2024-08-03 11:26:10] [redacted] HTTP GET /lookup
[2024-08-03 11:26:10] [redacted] HTTP 200 /lookup
[2024-08-03 11:26:10] Refreshing users data...
[2024-08-03 11:26:10] [redacted] HTTP GET /users.json
[2024-08-03 11:26:10] Updating account profile data...
[2024-08-03 11:26:10] [redacted] HTTP GET /users/user-redacted.json
[2024-08-03 11:26:11] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 11:26:11] [redacted] HTTP 200 /users.json
[2024-08-03 11:26:11] [redacted] HTTP 200 /img/avatar/user_medium.png
[2024-08-03 11:26:11] [redacted] HTTP 200 /users/user-redacted.json
[2024-08-03 11:26:11] ...users data refresh failed!
[2024-08-03 11:26:11] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
[2024-08-03 11:26:11] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-08-03 11:26:11] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
```


```
Passbolt:
Device: iPad
OS: 17.5.1
App: 1.19.0
[2024-08-03 11:03:03] Initializing the app...
[2024-08-03 11:03:03] ...app initialization completed!
[2024-08-03 11:03:03] Verifying data integrity...
[2024-08-03 11:03:03] ...data integrity verification finished
[2024-08-03 11:03:03] [6redacted] HTTP GET /lookup
[2024-08-03 11:03:03] [6redacted] HTTP 200 /lookup
[2024-08-03 11:03:03] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 11:03:03] Beginning authorization...
[2024-08-03 11:03:04] [redacted] HTTP 200 /img/avatar/user_medium.png
[2024-08-03 11:03:04] ...creating new access token...
[2024-08-03 11:03:04] ...fetching server public PGP key...
[2024-08-03 11:03:04] ...fetching server public RSA key...
[2024-08-03 11:03:04] [redacted] HTTP GET /auth/verify.json
[2024-08-03 11:03:04] [redacted] HTTP GET /auth/jwt/rsa.json
[2024-08-03 11:03:05] [redacted] HTTP 200 /auth/verify.json
[2024-08-03 11:03:05] [redacted] HTTP 200 /auth/jwt/rsa.json
[2024-08-03 11:03:05] Local timestamp: 1722682985
[2024-08-03 11:03:05] Server timestamp: 1722682985
[2024-08-03 11:03:05] Using time diff for session: -1
[2024-08-03 11:03:05] ...verifying server public PGP key...
[2024-08-03 11:03:05] ...preparing authorization challenge...
[2024-08-03 11:03:05] [redacted] HTTP POST /auth/jwt/login.json
[2024-08-03 11:03:06] [redacted] HTTP 200 /auth/jwt/login.json
[2024-08-03 11:03:06] Session created...
[2024-08-03 11:03:06] ...authorization succeeded!
[2024-08-03 11:03:06] Session auto locking enabled!
[2024-08-03 11:03:06] Verifying data integrity...
[2024-08-03 11:03:06] ...data integrity verification finished
[2024-08-03 11:03:06] Fetching server configuration...
[2024-08-03 11:03:06] [redacted] HTTP GET /settings.json
[2024-08-03 11:03:06] [redacted] HTTP 200 /settings.json
[2024-08-03 11:03:06] ...server configuration fetched!
[2024-08-03 11:03:06] Fetching rbacs configuration...
[2024-08-03 11:03:06] [redacted] HTTP GET /rbacs/me.json
[2024-08-03 11:03:06] [redacted] HTTP 200 /rbacs/me.json
[2024-08-03 11:03:06] ...rbacs configuration fetched!
[2024-08-03 11:03:06] [redacted] HTTP GET /lookup
[2024-08-03 11:03:06] [redacted] HTTP 200 /lookup
[2024-08-03 11:03:06] Refreshing users data...
[2024-08-03 11:03:06] [redacted] HTTP GET /users.json
[2024-08-03 11:03:06] Updating account profile data...
[2024-08-03 11:03:06] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 11:03:06] [redacted] HTTP GET /users/user-redacted.json
[2024-08-03 11:03:07] [redacted] HTTP 200 /img/avatar/user_medium.png
[2024-08-03 11:03:07] [redacted] HTTP 200 /users.json
[2024-08-03 11:03:07] [redacted] HTTP 200 /users/user-redacted.json
[2024-08-03 11:03:07] ...users data refresh failed!
[2024-08-03 11:03:07] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-08-03 11:03:07] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
[2024-08-03 11:03:07] ...account profile data updated!
[2024-08-03 11:03:09] [redacted] HTTP GET /img/avatar/user_medium.png
[2024-08-03 11:03:09] [redacted] HTTP 200 /img/avatar/user_medium.png
```

BR
Takalele

**Comment by Takalele** [comment]
@scadra

status-report and healthcheck are both without errors, Browser Plugin, Desktop Client and Android Mobile Clients are all working fine. Only the iOS Mobile clients are getting the NetworkResponseDecodingFailure error. :(

the ios client "downloads" /users.json?api-version=v2 from the server and throws the NetworkResponseDecodingFailure error on the display.
server logs:
```
10.0.6.67 - - [05/Aug/2024:18:59:06 +0000] "POST /auth/jwt/refresh.json HTTP/2.0" 200 1213 "-" "Passbolt/51 CFNetwork/1410.1 Darwin/22.6.0"
10.0.6.67 - - [05/Aug/2024:18:59:06 +0000] "GET /users.json?api-version=v2 HTTP/2.0" 200 63121 "-" "Passbolt/51 CFNetwork/1410.1 Darwin/22.6.0"
```

BR
Takalele

**Comment by GCaminero** [comment]
I had the same issue since I migrate from docker server version 4.0.2 to 4.10.1 (past 19th of december), both CE. Only in iOS. Web and Andriod are working fine.

This is the log of an iOS device:

```
Passbolt:
Device: iPhone
OS: 18.2
App: 1.21.0
----------
[2024-12-23 11:51:18] Initializing the app...
[2024-12-23 11:51:18] ...app initialization completed!
[2024-12-23 11:51:18] Verifying data integrity...
[2024-12-23 11:51:18] ...data integrity verification finished
[2024-12-23 11:51:18] [DDC3508F-DEA2-4A3D-A05A-B6361B986959] HTTP GET /lookup
[2024-12-23 11:51:18] [DDC3508F-DEA2-4A3D-A05A-B6361B986959] HTTP 200 /lookup
[2024-12-23 11:51:18] [B88E9B2B-46D9-4543-A03F-1EDAF6CDAE6E] HTTP GET /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:18] [582CF3E8-7795-4C28-A02B-FDA286545568] HTTP GET /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:19] Beginning authorization...
[2024-12-23 11:51:19] [B88E9B2B-46D9-4543-A03F-1EDAF6CDAE6E] HTTP 200 /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:19] [582CF3E8-7795-4C28-A02B-FDA286545568] HTTP 200 /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:19] ...creating new access token...
[2024-12-23 11:51:19] ...fetching server public PGP key...
[2024-12-23 11:51:19] ...fetching server public RSA key...
[2024-12-23 11:51:19] [9B143339-B107-4CCF-8B65-2F2DDF260C1E] HTTP GET /auth/verify.json
[2024-12-23 11:51:19] [7CEEF42C-D003-4AE5-AA51-D4701E3C6C56] HTTP GET /auth/jwt/rsa.json
[2024-12-23 11:51:20] [7CEEF42C-D003-4AE5-AA51-D4701E3C6C56] HTTP 200 /auth/jwt/rsa.json
[2024-12-23 11:51:20] [9B143339-B107-4CCF-8B65-2F2DDF260C1E] HTTP 200 /auth/verify.json
[2024-12-23 11:51:20] Local timestamp: 1734954680
[2024-12-23 11:51:20] Server timestamp: 1734954680
[2024-12-23 11:51:20] Using time diff for session: -1
[2024-12-23 11:51:20] ...verifying server public PGP key...
[2024-12-23 11:51:20] ...preparing authorization challenge...
[2024-12-23 11:51:20] [AC540B48-8E91-4078-A0B6-C2F83510262D] HTTP POST /auth/jwt/login.json
[2024-12-23 11:51:20] [AC540B48-8E91-4078-A0B6-C2F83510262D] HTTP 200 /auth/jwt/login.json
[2024-12-23 11:51:20] Session created...
[2024-12-23 11:51:20] ...authorization succeeded!
[2024-12-23 11:51:20] Session auto locking enabled!
[2024-12-23 11:51:20] Verifying data integrity...
[2024-12-23 11:51:20] ...data integrity verification finished
[2024-12-23 11:51:20] Fetching server configuration...
[2024-12-23 11:51:20] [B6F00D6A-638B-4C67-92A8-32488CE91758] HTTP GET /settings.json
[2024-12-23 11:51:20] [B6F00D6A-638B-4C67-92A8-32488CE91758] HTTP 200 /settings.json
[2024-12-23 11:51:20] ...server configuration fetched!
[2024-12-23 11:51:20] Fetching rbacs configuration...
[2024-12-23 11:51:20] [603D734D-ECA0-4308-974D-39388186E90E] HTTP GET /rbacs/me.json
[2024-12-23 11:51:20] [603D734D-ECA0-4308-974D-39388186E90E] HTTP 200 /rbacs/me.json
[2024-12-23 11:51:20] ...rbacs configuration fetched!
[2024-12-23 11:51:21] [CAF999B1-D327-4193-8283-625CB22F0DC6] HTTP GET /lookup
[2024-12-23 11:51:21] [CAF999B1-D327-4193-8283-625CB22F0DC6] HTTP 200 /lookup
[2024-12-23 11:51:21] Refreshing users data...
[2024-12-23 11:51:21] [1277966D-2EB9-4737-BB02-97D23EAFCE67] HTTP GET /users.json
[2024-12-23 11:51:21] Updating account profile data...
[2024-12-23 11:51:21] [1B94ADF7-955A-4AF8-B739-F5AE38D1CBCB] HTTP GET /users/e83c9fd1-fe7c-40aa-9f10-76704c52d76c.json
[2024-12-23 11:51:21] [F992C333-AF73-416C-86CA-856DDFAD0DDE] HTTP GET /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:21] [1277966D-2EB9-4737-BB02-97D23EAFCE67] HTTP 200 /users.json
[2024-12-23 11:51:21] ...users data refresh failed!
[2024-12-23 11:51:21] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
⮑ "path": 86
⮑ "file": PassboltNetworkOperations/NetworkResponseDecoder.swift
[2024-12-23 11:51:21] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
⮑ "path": 86
⮑ "file": PassboltNetworkOperations/NetworkResponseDecoder.swift
[2024-12-23 11:51:21] [1B94ADF7-955A-4AF8-B739-F5AE38D1CBCB] HTTP 200 /users/e83c9fd1-fe7c-40aa-9f10-76704c52d76c.json
[2024-12-23 11:51:21] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
⮑ "path": 86
⮑ "file": PassboltNetworkOperations/NetworkResponseDecoder.swift
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
⮑ "path": 101
⮑ "file": PassboltApp/MainTabsController.swift
[2024-12-23 11:51:21] [F992C333-AF73-416C-86CA-856DDFAD0DDE] HTTP 200 /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:25] Refreshing users data...
[2024-12-23 11:51:25] [7D171C14-35EB-4C24-91CA-BBD9E3EB013A] HTTP GET /users.json
[2024-12-23 11:51:25] [7D171C14-35EB-4C24-91CA-BBD9E3EB013A] HTTP 200 /users.json
[2024-12-23 11:51:25] ...users data refresh failed!
[2024-12-23 11:51:32] Wiping passphrase cache...
[2024-12-23 11:51:32] Requesting authorization...
[2024-12-23 11:51:32] [B7BC90AB-3E7E-4071-8466-6797BC0EDABB] HTTP GET /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:32] [3EBD95FB-FCB2-4486-86B0-91D39E6B3E84] HTTP GET /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:32] Beginning authorization...
[2024-12-23 11:51:32] [3EBD95FB-FCB2-4486-86B0-91D39E6B3E84] HTTP 200 /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:32] [B7BC90AB-3E7E-4071-8466-6797BC0EDABB] HTTP 200 /avatars/view/d269dfce-1eb7-480e-8151-bc30786384b0/medium.jpg
[2024-12-23 11:51:33] ...reusing access token...
[2024-12-23 11:51:33] Passphrase provided...
[2024-12-23 11:51:33] ...authorization succeeded!
[2024-12-23 11:51:33] Updating account profile data...
[2024-12-23 11:51:33] [F74143B3-8CD5-4BFA-988A-1E0B3D7A8A90] HTTP GET /users/e83c9fd1-fe7c-40aa-9f10-76704c52d76c.json
[2024-12-23 11:51:33] [F74143B3-8CD5-4BFA-988A-1E0B3D7A8A90] HTTP 200 /users/e83c9fd1-fe7c-40aa-9f10-76704c52d76c.json
[2024-12-23 11:51:33] ⚠️ NetworkResponseDecodingFailure
DiagnosticsContext:
•Failed to decode bad request response PassboltNetworkOperations/NetworkResponseDecoder.swift:86
⮑ "path": 86
⮑ "file": PassboltNetworkOperations/NetworkResponseDecoder.swift
•...account profile data update failed! PassboltApp/MainTabsController.swift:101
⮑ "path": 101
⮑ "file": PassboltApp/MainTabsController.swift
```

Any solution? Thanks all!!

**Comment by gw86** [comment]
Hi @GCaminero 

Sorry for such a long response time, but we have got and resolved a few of these NetworkResponseDecodingFailure errors, and we might have missed responding to this one. Sorry for that.

I hope you are not experiencing it anymore - is that true?

**Comment by rikwillems** [comment]
@gw86 No worries, thank you for all your efforts. We haven't seen the issue since a long time.
